/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Cagente;
import Control.Clogin;
import Modelo.Magente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFREDO CACONDA
 */
public class agente extends javax.swing.JFrame {

    /**
     * Creates new form entrada
     */
    int policia;
    public agente() {
        initComponents();
        Clogin c= new Clogin();
        policia=Integer.valueOf(c.recuprarValor(0));
        pesquisar("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtpesquisar = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbagente = new javax.swing.JTable();
        btnsalvar = new rojeru_san.RSButton();
        txtnip = new rojeru_san.RSMTextFull();
        txtnome = new rojeru_san.RSMTextFull();
        lbnome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setText("Apagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 290, 67, 23);

        txtpesquisar.setPlaceholder("PESQUISAR");
        getContentPane().add(txtpesquisar);
        txtpesquisar.setBounds(580, 270, 250, 42);

        tbagente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbagente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbagenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbagente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 322, 820, 190);

        btnsalvar.setText("GUARDAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvar);
        btnsalvar.setBounds(690, 220, 140, 40);

        txtnip.setPlaceholder("NIP");
        txtnip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnipKeyPressed(evt);
            }
        });
        getContentPane().add(txtnip);
        txtnip.setBounds(580, 160, 250, 42);

        txtnome.setPlaceholder("NOME COMPLETO");
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtnome);
        txtnome.setBounds(10, 160, 360, 42);

        lbnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbnome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_left_50px_1.png"))); // NOI18N
        lbnome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnomeMouseClicked(evt);
            }
        });
        getContentPane().add(lbnome);
        lbnome.setBounds(0, 0, 50, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UNIDADE DE TRANSITO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 290, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 40, 33, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BENGUELA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 70, 131, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/policia.png"))); // NOI18N
        jLabel6.setText("AGENTE REGULADOR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(632, 20, 200, 40);

        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N
        getContentPane().add(principal);
        principal.setBounds(0, 0, 848, 530);

        setSize(new java.awt.Dimension(845, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int codigo, id;
    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            txtnip.requestFocus();
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void txtnipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnipKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            salvar();
        }
    }//GEN-LAST:event_txtnipKeyPressed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void tbagenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbagenteMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            Object[]dados={"CANCELAR","EDITAR"};
            int valor=(int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, dados, dados[1]);
            if (valor==1) {
                id=1;
                codigo=(int) tbagente.getValueAt(tbagente.getSelectedRow(), 0);
                String nome=(String)tbagente.getValueAt(tbagente.getSelectedRow(), 1);
                int nip= (int) tbagente.getValueAt(tbagente.getSelectedRow(), 2);
            }
        } else {
        }
    }//GEN-LAST:event_tbagenteMouseClicked

    private void lbnomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnomeMouseClicked
        // TODO add your handling code here:
        new princpal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbnomeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Magente m = new Magente();
        Cagente c = new Cagente();
        codigo=(int) tbagente.getValueAt(tbagente.getSelectedRow(), 0);
         m.setId_agente(codigo);
         c.apagar(m);
         pesquisar("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnsalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel principal;
    private javax.swing.JTable tbagente;
    private rojeru_san.RSMTextFull txtnip;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpesquisar;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        Magente m = new Magente();
        Cagente c = new Cagente();
        
        String nome = txtnome.getText();
        int nip = Integer.valueOf(txtnip.getText());
        if (txtnip.getText().equals("") || txtnome.getText().equals("")) {
            m.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        } else {
            m.setNip(nip);
            m.setNome(nome);
            m.setId_policia(policia);
            c.salvar(m);
            if (id == 1) {
                m.setId_agente(codigo);
                m.setId_policia(policia);
                c.atualizar(m);
            }
        }
        pesquisar("");
        limpar();
    }

    public void pesquisar(String pesquisar) {
        Cagente f = new Cagente();
        DefaultTableModel dt = (DefaultTableModel) tbagente.getModel();
        Object[] recebe = {"CODIGO", "NOME", "NIP"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Magente m : f.listar(pesquisar)) {
            Object[] dados = {m.getId_agente(), m.getNome(), m.getNip()};
            dt.addRow(dados);
        }
    }

    private void limpar() {
        txtnip.setText("");
        txtnome.requestFocus();
        txtnome.setText("");
    }
}
