/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Cautomobilista;
import Control.Clogin;
import Modelo.Mautomobilista;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFREDO CACONDA
 */
public class automobilista extends javax.swing.JFrame {

    /**
     * Creates new form entrada
     */
    String idpolicia;
    public automobilista() {
        initComponents();
        Control.Clogin login= new Clogin();
        idpolicia= login.recuprarValor(0);
        pesquisar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        jButton1 = new javax.swing.JButton();
        lbnome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnsalvar = new rojeru_san.RSButton();
        txtpesquisar = new rojeru_san.RSMTextFull();
        txtnome = new rojeru_san.RSMTextFull();
        btnsalvar1 = new rojeru_san.RSButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbfuncionario = new javax.swing.JTable();
        txttelefone = new rojeru_san.RSMTextFull();
        txtendereco = new rojeru_san.RSMTextFull();
        txtdatacaducidade = new javax.swing.JFormattedTextField();
        txtcarta = new rojeru_san.RSMTextFull();
        txtdataentrada = new javax.swing.JFormattedTextField();
        principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setText("Apagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 330, 67, 23);

        lbnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbnome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_left_50px_1.png"))); // NOI18N
        lbnome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnomeMouseClicked(evt);
            }
        });
        getContentPane().add(lbnome);
        lbnome.setBounds(0, 0, 50, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UNIDADE DE TRANSITO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 290, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 40, 33, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BENGUELA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 70, 131, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PROPRIETARIO.png"))); // NOI18N
        jLabel6.setText("AUTOMOBILISTA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(662, 20, 170, 30);

        btnsalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_edit_property_30px.png"))); // NOI18N
        btnsalvar.setText("EDITAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvar);
        btnsalvar.setBounds(530, 250, 150, 40);

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(txtpesquisar);
        txtpesquisar.setBounds(480, 300, 350, 42);

        txtnome.setPlaceholder("NOME ");
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });
        getContentPane().add(txtnome);
        txtnome.setBounds(20, 120, 280, 42);

        btnsalvar1.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnsalvar1.setText("GUARDAR");
        btnsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvar1);
        btnsalvar1.setBounds(690, 250, 140, 40);

        tbfuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbfuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbfuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbfuncionario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 360, 810, 150);

        txttelefone.setPlaceholder("TELEFONE/EMAIL");
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        txttelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefoneKeyPressed(evt);
            }
        });
        getContentPane().add(txttelefone);
        txttelefone.setBounds(320, 120, 250, 42);

        txtendereco.setPlaceholder("ENDREÇO");
        txtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoActionPerformed(evt);
            }
        });
        txtendereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtenderecoKeyPressed(evt);
            }
        });
        getContentPane().add(txtendereco);
        txtendereco.setBounds(580, 120, 250, 42);

        txtdatacaducidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA DE CADUCIDADE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        try {
            txtdatacaducidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatacaducidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatacaducidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdatacaducidadeKeyPressed(evt);
            }
        });
        getContentPane().add(txtdatacaducidade);
        txtdatacaducidade.setBounds(580, 180, 250, 60);

        txtcarta.setPlaceholder("NÚMERO DA CARTA");
        txtcarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcartaActionPerformed(evt);
            }
        });
        txtcarta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcartaKeyPressed(evt);
            }
        });
        getContentPane().add(txtcarta);
        txtcarta.setBounds(20, 180, 280, 42);

        txtdataentrada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA DE EMISSÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        try {
            txtdataentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdataentrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtdataentrada);
        txtdataentrada.setBounds(320, 180, 250, 60);

        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N
        getContentPane().add(principal);
        principal.setBounds(0, 0, 848, 530);

        setSize(new java.awt.Dimension(849, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void tbfuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbfuncionarioMouseClicked
        if (evt.getClickCount()==2) {
            int idautomobilista=(int)tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 0);
            String nome=(String)tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 1);
            infracao f= new infracao(idautomobilista,nome);
            f.setVisible(true);
            this.dispose();}
        
        
        
    }//GEN-LAST:event_tbfuncionarioMouseClicked

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        if (tbfuncionario.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "SELECIONA O ITEM QUE PRETENDE EDITAR");
        } else {
            id = (int) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 0);
            txtnome.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 1));
            txtendereco.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 2));
            txttelefone.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 3));
            txtcarta.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 4));
//            txtdatacaducidade.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 6));
//            txtdataentrada.setText((String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 5));
            String datae = (String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 5);
            String data = (String) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 6);
             txtdatacaducidade.setText("" + data.replace('-', '/'));
             txtdataentrada.setText("" + datae.replace('-', '/'));
            btnsalvar1.setText("ACTUALIZAR");
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            txttelefone.requestFocus();
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void txttelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtendereco.requestFocus();
        }
    }//GEN-LAST:event_txttelefoneKeyPressed

    private void txtenderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtenderecoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==10) {
            txtcarta.requestFocus();
        }
    }//GEN-LAST:event_txtenderecoKeyPressed

    private void txtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenderecoActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed
    int codigo, id;
    private void btnsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar1ActionPerformed
        // TODO add your handling code here:
        if (codigo == 0) {
            salvar();
            pesquisar("");
        } else {
            salvar();
            btnsalvar1.setText("GUARDAR");
        }
    }//GEN-LAST:event_btnsalvar1ActionPerformed

    private void lbnomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnomeMouseClicked
        // TODO add your handling code here:
        new princpal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbnomeMouseClicked

    private void txtcartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcartaActionPerformed

    private void txtcartaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcartaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            txtdataentrada.getText();
        }
    }//GEN-LAST:event_txtcartaKeyPressed

    private void txtdatacaducidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatacaducidadeKeyPressed
        if (evt.getKeyCode()==10) {
            salvar();
        }
    }//GEN-LAST:event_txtdatacaducidadeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Mautomobilista f = new Mautomobilista();
        Cautomobilista c = new Cautomobilista();
        id = (int) tbfuncionario.getValueAt(tbfuncionario.getSelectedRow(), 0);
        f.setId_automobilista(id);
                c.apagar(f);
                pesquisar("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(automobilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(automobilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(automobilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(automobilista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new automobilista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnsalvar;
    private rojeru_san.RSButton btnsalvar1;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel principal;
    private javax.swing.JTable tbfuncionario;
    private rojeru_san.RSMTextFull txtcarta;
    private javax.swing.JFormattedTextField txtdatacaducidade;
    private javax.swing.JFormattedTextField txtdataentrada;
    private rojeru_san.RSMTextFull txtendereco;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpesquisar;
    private rojeru_san.RSMTextFull txttelefone;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
       Mautomobilista f = new Mautomobilista();
        Cautomobilista c = new Cautomobilista();
        
        String nome = txtnome.getText();
        String telefone = txttelefone.getText();
        String carta = txtcarta.getText();
        String endereco = txtendereco.getText();
        String dataentrada =txtdataentrada.getText();
        String datacaducidade=txtdatacaducidade.getText();
        if (txtcarta.getText().equals("")|| txtdatacaducidade.getText().equals("    /  /  ")|| txtendereco.getText().equals("")
                || txtnome.getText().equals("")|| txttelefone.getText().equals("")
                || txtdataentrada.getText().equals("    /  /  ")){
            
            f.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        } else {
            f.setEndereco(endereco);
            f.setDatae(dataentrada);
            f.setCaducidade(datacaducidade);
            f.setNome(nome);
            f.setCarta(carta);
            f.setTelefone(telefone);
            f.setIdp(Integer.valueOf(idpolicia));
            if (id == 0) {
                c.salvar(f);
            } else {
                f.setId_automobilista(id);
                c.atualizar(f);
                btnsalvar1.setText("GUARDAR");
            }
        }
        apagar();

    }

    public void pesquisar(String pesquisar) {
        Cautomobilista f = new Cautomobilista();
        DefaultTableModel dt = (DefaultTableModel) tbfuncionario.getModel();
        Object[] recebe = {"CODIGO", "NOME", "ENDEREÇO","TELEFONE/EMAIL",
            "NUMERO DA CARTA", "DATA DE EMISSÃO", "DATA DE CADUCIDADE"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Mautomobilista m : f.listar(pesquisar)) {
            Object[] dado = {m.getId_automobilista(), m.getNome(), m.getEndereco(),m.getTelefone(),
                m.getCarta(), m.getDatae(),m.getCaducidade()};
            dt.addRow(dado);
        }
    }

    private void apagar() {
        txtcarta.setText("");
        txtendereco.setText("");
        txtnome.setText("");
        txtdatacaducidade.setText("");
        txttelefone.setText("");
        txtdataentrada.setText("");
        txtcarta.setText("");
        
    }
    private String  buscarData(Date data) {
        SimpleDateFormat f = new SimpleDateFormat("yyyy/MM/dd");
        return f.format( data);
    }
}
