/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CVinfracao;
import Control.Cagente;
import Control.Cinfracao;
import Control.Clogin;
import Modelo.Magente;
import Modelo.Minfracao;
import Modelo.Mvenfracao;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFREDO CACONDA
 */
public class infracao extends javax.swing.JFrame {

    /**
     * Creates new form entrada
     */
    public infracao() {
        initComponents();
        pesquisar("");
        agente("");
        btnsalvar2.setEnabled(false);
        Control.Clogin c = new Clogin();
        idpolicia = Integer.valueOf(c.recuprarValor(0));
    }

    String automobilista;
    int idautomobilista, idpolicia;

    infracao(int idpp, String nome) {
        initComponents();
        automobilista = nome;
        txtnome.setText(automobilista);
        Control.Clogin c = new Clogin();
        lbnome.setText(c.recuprarValor(1));
        idpolicia = Integer.valueOf(c.recuprarValor(0));
        idautomobilista = idpp;
        pesquisar("");
        agente("");
        btnsalvar2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        jLabel2 = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtnome = new rojeru_san.RSMTextFull();
        txtdisciplina_rodoviaria = new rojeru_san.RSMTextFull();
        txtinfracao = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbinfrator = new javax.swing.JTable();
        txtpesquisar = new rojeru_san.RSMTextFull();
        btnsalvar = new rojeru_san.RSButton();
        cblocal = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbagente = new javax.swing.JTable();
        txtnipagente = new rojeru_san.RSMTextFull();
        jPanel2 = new javax.swing.JPanel();
        txtdatap = new javax.swing.JFormattedTextField();
        btnsalvar2 = new rojeru_san.RSButton();
        cbestadopago = new javax.swing.JComboBox();
        txtdaentrada = new javax.swing.JFormattedTextField();
        btnsalvar1 = new rojeru_san.RSButton();
        txtmulta = new rojeru_san.RSMTextFull();
        jButton1 = new javax.swing.JButton();
        principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UTB");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 10, 290, 29);

        lbnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbnome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_left_50px_1.png"))); // NOI18N
        lbnome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnomeMouseClicked(evt);
            }
        });
        getContentPane().add(lbnome);
        lbnome.setBounds(0, 0, 50, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_private_48px.png"))); // NOI18N
        jLabel6.setText("INFRAÇÃO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(662, 20, 170, 48);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtnome.setEnabled(false);
        txtnome.setPlaceholder("NOME ");
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        txtdisciplina_rodoviaria.setPlaceholder("DISCIPLINA RODOVIARIA");
        txtdisciplina_rodoviaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdisciplina_rodoviariaActionPerformed(evt);
            }
        });
        txtdisciplina_rodoviaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdisciplina_rodoviariaKeyPressed(evt);
            }
        });

        txtinfracao.setPlaceholder("INFRAÇÃO");
        txtinfracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinfracaoActionPerformed(evt);
            }
        });
        txtinfracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinfracaoKeyPressed(evt);
            }
        });

        tbinfrator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbinfrator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbinfratorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbinfrator);

        txtpesquisar.setPlaceholder("Pesquisar");
        txtpesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisarKeyReleased(evt);
            }
        });

        btnsalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        cblocal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cblocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LOCAL DE ATUAÇÃO", "BENGUELA", "BOCOIO", "BALOMBO", "BAIA FARTA", "CATUMBELA", "CHONGOROI", "CUBAL", "GANDA", "LOBITO", "CAIBAMBO" }));
        cblocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cblocalKeyPressed(evt);
            }
        });

        tbagente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbagente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbagenteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbagente);

        txtnipagente.setPlaceholder("Agente regulador");
        txtnipagente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnipagenteKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAINEL DE PAGAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        txtdatap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA DO PAGAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        try {
            txtdatap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdatap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdatap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdatapKeyPressed(evt);
            }
        });

        btnsalvar2.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnsalvar2.setText("FAZER PAGAMENTO");
        btnsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar2ActionPerformed(evt);
            }
        });

        cbestadopago.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbestadopago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ESTADO DE PAGAMENTO", "PAGO", "NÃO PAGO" }));
        cbestadopago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestadopagoActionPerformed(evt);
            }
        });
        cbestadopago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbestadopagoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtdatap, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(493, 493, 493)
                    .addComponent(btnsalvar2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(cbestadopago, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(txtdatap, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(btnsalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(cbestadopago, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        txtdaentrada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA DE INFRAÇÃO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        try {
            txtdaentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdaentrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdaentrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdaentrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdaentradaKeyPressed(evt);
            }
        });

        btnsalvar1.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_print_30px.png"))); // NOI18N
        btnsalvar1.setText("IMPRIMIR TUDO");
        btnsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar1ActionPerformed(evt);
            }
        });

        txtmulta.setPlaceholder("VALOR DA MULTA");
        txtmulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmultaKeyPressed(evt);
            }
        });

        jButton1.setText("apagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdisciplina_rodoviaria, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(txtnome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtinfracao, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnipagente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtdaentrada))
                            .addComponent(cblocal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtmulta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnsalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnipagente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtinfracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdaentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdisciplina_rodoviaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtmulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cblocal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(10, 70, 830, 450);

        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N
        getContentPane().add(principal);
        principal.setBounds(0, 0, 848, 530);

        setSize(new java.awt.Dimension(846, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtinfracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinfracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinfracaoActionPerformed
    int cont, id, poli;
    String multaa, auto, datap, estadoo, infracao, dataentrada, disciplina, local, n_cartaa;
    private void tbinfratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbinfratorMouseClicked
        id = (int) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 0);
        if (evt.getClickCount() == 2) {
            Object[] recebe = {"CANCELAR", "EDITAR", "PAGAMENTO", "IMPRIMIR", "IMPRIMIR TODAS INFRAÇÕES"};//declaramos uma vetor objecto que vai armazenar os itens selecionado
            int n = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, recebe, recebe[1]);
            if (n == 1) {
                auto = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 1);
                txtnome.setText("" + auto);//virá a parte do nome da view
                n_cartaa = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 2);
                String idagent = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 3);
                txtnipagente.setText("" + idagent);
               // idagente = Integer.valueOf(idagent);
                infracao = ((String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 4));
                txtinfracao.setText(infracao);
                dataentrada = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 5);
                txtdaentrada.setText("" + dataentrada.replace('-', '/'));
                local = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 7);
                cblocal.setSelectedItem(local);
                disciplina = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 6);
                txtdisciplina_rodoviaria.setText(disciplina);
               double multaa = ((double) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 9));
                txtmulta.setText(""+multaa);
                datap = ((String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 10));
                txtdatap.setText("" + datap.replace("-", "/"));
                txtdaentrada.setEnabled(!false);
                txtnipagente.setEnabled(!false);
                txtinfracao.setEnabled(!false);
                txtdatap.setEnabled(!true);
                txtmulta.setEnabled(true);
                cblocal.setEnabled(!false);
                txtdisciplina_rodoviaria.setEnabled(!false);
                tbagente.setEnabled(false);
                cont = 1;
                btnsalvar.setText("ACTUALIZAR");
                //atualizar();
            } else {
                if (n == 2) {
                    auto = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 1);
                    txtnome.setText("" + auto);//virá a parte do nome da view
                    n_cartaa = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 2);
                    String idagent = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 3);
                    btnsalvar2.setEnabled(!false);
                    txtnipagente.setText("" + idagent);
                    // idagente = Integer.valueOf(idagent);
                    infracao = ((String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 4));
                    txtinfracao.setText(infracao);
                    dataentrada = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 5);
                    txtdaentrada.setText("" + dataentrada.replace('-', '/'));
                    local = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 7);
                    cblocal.setSelectedItem(local);
                    disciplina = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 6);
                    txtdisciplina_rodoviaria.setText(disciplina);
                    datap = ((String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 10));
                    //txtdatap.setText("" + datap.replace("-", "/"));
                    multaa = ((String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 9));
                    txtmulta.setText(multaa);
                    estadoo = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 8);
                    txtdaentrada.setEnabled(false);
                    txtmulta.setEnabled(true);
                    txtnipagente.setEnabled(false);
                    txtinfracao.setEnabled(false);
                    txtdatap.setEnabled(true);
                    txtmulta.setEnabled(true);
                    cblocal.setEnabled(!false);
                    tbagente.setEnabled(false);
                    txtdisciplina_rodoviaria.setEnabled(false);
                    btnsalvar.setText("PAGAMENTO");
                    cont = 1;
                }
                if (n == 3) {
                    CVinfracao f = new CVinfracao();
                    f.imprimir(id + "");
                }
                if (n == 4) {
                    n_cartaa = (String) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 2);
                    CVinfracao f = new CVinfracao();
                    f.imprimir1(n_cartaa + "");
                }
            }
        }
    }//GEN-LAST:event_tbinfratorMouseClicked

    private void txtpesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarKeyReleased
        // TODO add your handling code here:
        pesquisar(txtpesquisar.getText());
    }//GEN-LAST:event_txtpesquisarKeyReleased

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtnipagente.requestFocus();
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void txtdisciplina_rodoviariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdisciplina_rodoviariaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            cblocal.requestFocus();
        }
    }//GEN-LAST:event_txtdisciplina_rodoviariaKeyPressed

    private void txtinfracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinfracaoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtdaentrada.requestFocus();
        }
    }//GEN-LAST:event_txtinfracaoKeyPressed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        if (cont == 0) {
            salvar();
            pesquisar("");
        }
        if (cont == 1) {
            atualizar();
            pesquisar("");
            btnsalvar.setText("ACTUALIZAR");
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtmultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmultaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmultaKeyPressed
    int idagente;
    private void tbagenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbagenteMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            idagente = (int) tbagente.getValueAt(tbagente.getSelectedRow(), 0);
            txtnipagente.setText((String) tbagente.getValueAt(tbagente.getSelectedRow(), 1));
            JOptionPane.showMessageDialog(this, "AGENTE SELECIONADO");
        }

    }//GEN-LAST:event_tbagenteMouseClicked

    private void txtdisciplina_rodoviariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdisciplina_rodoviariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdisciplina_rodoviariaActionPerformed

    private void txtnipagenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnipagenteKeyReleased
        // TODO add your handling code here:
        agente(txtpesquisar.getText());
    }//GEN-LAST:event_txtnipagenteKeyReleased

    private void lbnomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnomeMouseClicked
        // TODO add your handling code here:
        new princpal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbnomeMouseClicked

    private void btnsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar1ActionPerformed
        // TODO add your handling code here:
        CVinfracao f = new CVinfracao();
        f.imprimirtudo();
    }//GEN-LAST:event_btnsalvar1ActionPerformed

    private void txtdaentradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaentradaKeyPressed
        if (evt.getKeyCode() == 10) {
            txtdisciplina_rodoviaria.requestFocus();
        }
    }//GEN-LAST:event_txtdaentradaKeyPressed

    private void cblocalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cblocalKeyPressed
        if (evt.getKeyCode() == 10) {
            salvar();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cblocalKeyPressed

    private void txtdatapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatapKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtmulta.requestFocus();
        }
    }//GEN-LAST:event_txtdatapKeyPressed

    private void btnsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar2ActionPerformed
        // TODO add your handling code here:
        atualizarpaga();
    }//GEN-LAST:event_btnsalvar2ActionPerformed

    private void cbestadopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestadopagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbestadopagoActionPerformed

    private void cbestadopagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbestadopagoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbestadopagoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Minfracao f = new Minfracao();
        Cinfracao c = new Cinfracao();
        id = (int) tbinfrator.getValueAt(tbinfrator.getSelectedRow(), 0); 
         f.setId_infracao(id);
         c.apagar(f);
         pesquisar("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnsalvar;
    private rojeru_san.RSButton btnsalvar1;
    private rojeru_san.RSButton btnsalvar2;
    private javax.swing.JComboBox cbestadopago;
    private javax.swing.JComboBox cblocal;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel principal;
    private javax.swing.JTable tbagente;
    private javax.swing.JTable tbinfrator;
    private javax.swing.JFormattedTextField txtdaentrada;
    private javax.swing.JFormattedTextField txtdatap;
    private rojeru_san.RSMTextFull txtdisciplina_rodoviaria;
    private rojeru_san.RSMTextFull txtinfracao;
    private rojeru_san.RSMTextFull txtmulta;
    private rojeru_san.RSMTextFull txtnipagente;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtpesquisar;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        Minfracao f = new Minfracao();
        Cinfracao c = new Cinfracao();
        String infraacao = txtinfracao.getText();
        String disciiplina = txtdisciplina_rodoviaria.getText();
        String localizacao = (String) cblocal.getSelectedItem();
        String dataatuacao = txtdaentrada.getText();
        if (txtdisciplina_rodoviaria.getText().equals("") || txtdaentrada.getText().equals("")
                || txtinfracao.getText().equals("") && cblocal.getSelectedIndex() == 0) {
            f.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        } else {
            f.setInfracao(infraacao);
            f.setData_emissao(dataatuacao);
            f.setDisciplina(disciiplina);
            f.setLocal_de_atuacao(localizacao);
            f.setAgente(idagente);
            f.setMulta(txtmulta.getText());
            f.setEsta_de_pagamento("não pago");
            f.setPolicia(idpolicia);
            f.setIdautomobilista(idautomobilista);
            c.salvar(f);
            apagar();
            pesquisar("");
        }
    }

    private void atualizar() {
        Minfracao f = new Minfracao();
        Cinfracao c = new Cinfracao();
        infracao = txtinfracao.getText();
        disciplina = txtdisciplina_rodoviaria.getText();
        local = (String) cblocal.getSelectedItem();
        dataentrada = txtdaentrada.getText();
        multaa = txtmulta.getText();
        datap = txtdaentrada.getText();
        if (txtdisciplina_rodoviaria.getText().equals("") || txtdaentrada.getText().equals("")
                || txtinfracao.getText().equals("") && cblocal.getSelectedIndex() == 0) {
            f.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        } else {
            
            f.setId_infracao(id);
            f.setPolicia(idpolicia);
            f.setInfracao(infracao);
            f.setData_emissao(dataentrada);
            f.setDisciplina(disciplina);
            f.setLocal_de_atuacao(local);
//            f.setAgente(idagente);
            f.setMulta(multaa);
            c.atualizar(f);
        }
        apagar();
        pesquisar("");
    }

    private void atualizarpaga() {
        Minfracao f = new Minfracao();
        Cinfracao c = new Cinfracao();

        estadoo = (String) cbestadopago.getSelectedItem();
        datap = txtdatap.getText();

        f.setId_infracao(id);

        f.setData_do_pagamento(datap);
        f.setEsta_de_pagamento(estadoo);
        c.atualizarM(f);

        apagar();
        pesquisar("");
        c.imprimir(id + "");
    }

    public void pesquisar(String pesquisar) {
        CVinfracao inf = new CVinfracao();
        DefaultTableModel dt = (DefaultTableModel) tbinfrator.getModel();
        Object[] recebe = {"CODIGO", "AUTOMOBILISTA", "NÚMERO DA CARTA", "AGENTE", "INFRAÇÃO", "DATA DE ATUAÇÃO", "DISCIPLINA RODOVIARIA",
            "LOCAL DE ATUAÇÃO", "ESTADO DE PAGAMENTO", "MULTA", "DATA DE PAGAMENTO"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Mvenfracao m : inf.listar(pesquisar)) {
            Object[] dado = {m.getIdin(), m.getAutomobilista(), m.getN_carta(), m.getAgente(), m.getInfracao(),
                m.getData_da_atuacao(), m.getDisciplina_rodoviaria(), m.getLocal_de_atuacao(),
                m.getEstado_de_pagamento(), m.getMulta(), m.getData_do_pagamento()};
            dt.addRow(dado);
        }
    }

    private void apagar() {
        txtdisciplina_rodoviaria.setText("");
        txtnipagente.setText("");
        txtnome.setText("");
        txtinfracao.setText("");
        txtdaentrada.setText("");
        txtmulta.setText("");

    }

    private String buscarData(Date data) {
        SimpleDateFormat f = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        return f.format(data);
    }

    private void agente(String valor) {
        Cagente f = new Cagente();
        DefaultTableModel dt = (DefaultTableModel) tbagente.getModel();
        Object[] recebe = {"CODIGO", "NOME", "NIP"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Magente m : f.listar(valor)) {
            Object[] dados = {m.getId_agente(), m.getNome(), m.getNip()};
            dt.addRow(dados);
        }
    }

}
