/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Cpolicia;
import Modelo.Mpolicia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFREDO CACONDA
 */
public class policia extends javax.swing.JFrame {

    /**
     * Creates new form entrada
     */
    public policia() {
        initComponents();
        pesquisar("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        REGISTRO = new javax.swing.JPanel();
        txtnome = new rojeru_san.RSMTextFull();
        cbgenero = new javax.swing.JComboBox();
        txttelefone = new rojeru_san.RSMTextFull();
        txtnomedopai = new rojeru_san.RSMTextFull();
        cbcargo = new javax.swing.JComboBox();
        txtnip = new rojeru_san.RSMTextFull();
        btnsalvar = new rojeru_san.RSButton();
        txtnomedamae = new rojeru_san.RSMTextFull();
        txtmunicipio = new rojeru_san.RSMTextFull();
        txtprovincia = new rojeru_san.RSMTextFull();
        txtusuario = new rojeru_san.RSMTextFull();
        txtbi = new javax.swing.JFormattedTextField();
        txtsenha = new rojeru_san.RSMTextFull();
        TABELA = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpolicia = new javax.swing.JTable();
        txtpesquisar1 = new rojeru_san.RSMTextFull();
        btapagar = new rojeru_san.RSButton();
        btnsalvar2 = new rojeru_san.RSButton();
        principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BENGUELA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 70, 131, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/policia.png"))); // NOI18N
        jLabel6.setText("AGENTE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(730, 20, 102, 40);

        lbnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbnome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_left_50px_1.png"))); // NOI18N
        lbnome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnomeMouseClicked(evt);
            }
        });
        getContentPane().add(lbnome);
        lbnome.setBounds(0, 0, 50, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 40, 33, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UNIDADE DE TRANSITO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 290, 29);

        REGISTRO.setBackground(new java.awt.Color(255, 255, 255));

        txtnome.setPlaceholder("NOME  COMPLETO");
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        cbgenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbgenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONAR O GENERO", "MASCULINO", "FEMENINO" }));
        cbgenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbgeneroKeyPressed(evt);
            }
        });

        txttelefone.setPlaceholder("TELEFONE/EMAIL");
        txttelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefoneActionPerformed(evt);
            }
        });
        txttelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefoneKeyPressed(evt);
            }
        });

        txtnomedopai.setPlaceholder("NOME DO PAI");
        txtnomedopai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomedopaiKeyPressed(evt);
            }
        });

        cbcargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbcargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR O CARGO", "COMANDANTE", "AGENTE" }));
        cbcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbcargoKeyPressed(evt);
            }
        });

        txtnip.setPlaceholder("NIP");
        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });
        txtnip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnipKeyPressed(evt);
            }
        });

        btnsalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salvar.png"))); // NOI18N
        btnsalvar.setText("GUARDAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        txtnomedamae.setPlaceholder("NOME DA MÃE");
        txtnomedamae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomedamaeKeyPressed(evt);
            }
        });

        txtmunicipio.setPlaceholder("MUNICIPIO");
        txtmunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmunicipioKeyPressed(evt);
            }
        });

        txtprovincia.setPlaceholder("PROVINCIA");
        txtprovincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprovinciaKeyPressed(evt);
            }
        });

        txtusuario.setPlaceholder("USUÁRIO");
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusuarioKeyPressed(evt);
            }
        });

        txtbi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NUMERO DO BI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N
        try {
            txtbi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtbi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbiKeyPressed(evt);
            }
        });

        txtsenha.setPlaceholder("SENHA");
        txtsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout REGISTROLayout = new javax.swing.GroupLayout(REGISTRO);
        REGISTRO.setLayout(REGISTROLayout);
        REGISTROLayout.setHorizontalGroup(
            REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTROLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(REGISTROLayout.createSequentialGroup()
                        .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnomedopai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTROLayout.createSequentialGroup()
                        .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomedamae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbgenero, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtprovincia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbi, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtsenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTROLayout.createSequentialGroup()
                        .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTROLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        REGISTROLayout.setVerticalGroup(
            REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTROLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomedopai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnomedamae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        jTabbedPane1.addTab("REGISTRO DE UTILIZADOR", REGISTRO);

        TABELA.setBackground(new java.awt.Color(255, 255, 255));

        tbpolicia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpolicia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpoliciaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbpolicia);

        txtpesquisar1.setPlaceholder("Pesquisar");
        txtpesquisar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisar1KeyReleased(evt);
            }
        });

        btapagar.setBackground(new java.awt.Color(204, 204, 204));
        btapagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btapagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close.png"))); // NOI18N
        btapagar.setText("APAGAR");
        btapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btapagarActionPerformed(evt);
            }
        });

        btnsalvar2.setBackground(new java.awt.Color(204, 204, 204));
        btnsalvar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_print_30px.png"))); // NOI18N
        btnsalvar2.setText("IMPRIMIR TUDO");
        btnsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TABELALayout = new javax.swing.GroupLayout(TABELA);
        TABELA.setLayout(TABELALayout);
        TABELALayout.setHorizontalGroup(
            TABELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TABELALayout.createSequentialGroup()
                .addGroup(TABELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TABELALayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(txtpesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TABELALayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(TABELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TABELALayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(btnsalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(656, Short.MAX_VALUE)))
        );
        TABELALayout.setVerticalGroup(
            TABELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TABELALayout.createSequentialGroup()
                .addGroup(TABELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TABELALayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtpesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TABELALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btapagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(TABELALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TABELALayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(btnsalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("TABELA", TABELA);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 100, 830, 420);

        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N
        getContentPane().add(principal);
        principal.setBounds(0, -20, 848, 570);

        setSize(new java.awt.Dimension(847, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefoneActionPerformed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            cbgenero.requestFocus();
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void cbgeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbgeneroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtnip.requestFocus();
        }
    }//GEN-LAST:event_cbgeneroKeyPressed

    private void txttelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtusuario.requestFocus();
        }
    }//GEN-LAST:event_txttelefoneKeyPressed

    private void cbcargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbcargoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==10) {
            txttelefone.requestFocus();
        }
    }//GEN-LAST:event_cbcargoKeyPressed

    private void txtnomedopaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomedopaiKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==10) {
            txtnomedamae.requestFocus();
        }
    }//GEN-LAST:event_txtnomedopaiKeyPressed

    private void txtnipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnipKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==10) {
            txtnomedopai.requestFocus();
        }
    }//GEN-LAST:event_txtnipKeyPressed

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed
    int codigo, id;
    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        if (codigo ==0) {
            salvar();
            pesquisar("");
        } else {
            salvar();
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtnomedamaeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomedamaeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            txtbi.requestFocus();
        }
    }//GEN-LAST:event_txtnomedamaeKeyPressed

    private void txtmunicipioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmunicipioKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==10) {
            txtprovincia.requestFocus();
        }
    }//GEN-LAST:event_txtmunicipioKeyPressed

    private void txtprovinciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprovinciaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()==10) {
            cbcargo.requestFocus();
        }
    }//GEN-LAST:event_txtprovinciaKeyPressed

    private void tbpoliciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpoliciaMouseClicked
        // TODO add your handling code here:
         codigo = (int) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 0);
        if (evt.getClickCount() == 2) {
            Object[] recebe = {"Cancelar", "Editar", "Imprimir"};//declaramos uma vetor objecto que vai armazenar os itens selecionado
            int n = (int) JOptionPane.showOptionDialog(this, "O QUE DESEJA?", "AVISO",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, recebe, recebe[1]);
            if (n==0) {
                limpar();
            } 
                if (n == 1) {
                    id=1;
                    txtnome.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 1));
                    cbgenero.setSelectedItem((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 2));
                    txtnip.setText(""+(int)(tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 3)));
                    txtnomedopai.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 4));
                    txtnomedamae.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 5));
                    txtbi.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 6));
                    txtmunicipio.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 7));
                    txtprovincia.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 8));
                    cbcargo.setSelectedItem((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 9));
                    txttelefone.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 10));
                    txtusuario.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 11));
                    txtsenha.setText((String) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 12));
                    jTabbedPane1.setSelectedIndex(0);
                }
                if (n == 2) {
                    Cpolicia f = new Cpolicia();
                    f.imprimir(codigo + "");
                
            }
        }
    }//GEN-LAST:event_tbpoliciaMouseClicked

    private void txtpesquisar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisar1KeyReleased

    private void txtusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            txtsenha.requestFocus();
        }
    }//GEN-LAST:event_txtusuarioKeyPressed

    private void lbnomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnomeMouseClicked
        // TODO add your handling code here:
        new princpal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbnomeMouseClicked

    private void btapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btapagarActionPerformed
        // TODO add your handling code here:
        codigo = (int) tbpolicia.getValueAt(tbpolicia.getSelectedRow(), 0);
        Mpolicia m = new Mpolicia();
        m.setIdpolicia(codigo);
        Cpolicia p= new Cpolicia();
        p.apagar(m);
        pesquisar("");
    }//GEN-LAST:event_btapagarActionPerformed

    private void txtsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsenhaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaKeyPressed

    private void txtbiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            txtmunicipio.requestFocus();
        }
    }//GEN-LAST:event_txtbiKeyPressed

    private void btnsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar2ActionPerformed
        // TODO add your handling code here:
         Cpolicia p= new Cpolicia();
        p.imprimirtudo();
    }//GEN-LAST:event_btnsalvar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(policia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(policia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(policia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(policia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new policia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel REGISTRO;
    private javax.swing.JPanel TABELA;
    private rojeru_san.RSButton btapagar;
    private rojeru_san.RSButton btnsalvar;
    private rojeru_san.RSButton btnsalvar2;
    private javax.swing.JComboBox cbcargo;
    private javax.swing.JComboBox cbgenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel principal;
    private javax.swing.JTable tbpolicia;
    private javax.swing.JFormattedTextField txtbi;
    private rojeru_san.RSMTextFull txtmunicipio;
    private rojeru_san.RSMTextFull txtnip;
    private rojeru_san.RSMTextFull txtnome;
    private rojeru_san.RSMTextFull txtnomedamae;
    private rojeru_san.RSMTextFull txtnomedopai;
    private rojeru_san.RSMTextFull txtpesquisar1;
    private rojeru_san.RSMTextFull txtprovincia;
    private rojeru_san.RSMTextFull txtsenha;
    private rojeru_san.RSMTextFull txttelefone;
    private rojeru_san.RSMTextFull txtusuario;
    // End of variables declaration//GEN-END:variables

    private void salvar() {
        Mpolicia m = new Mpolicia();
        Cpolicia c = new Cpolicia();
        String nome = txtnome.getText();
        String genero = (String) cbgenero.getSelectedItem();
        int nip = Integer.valueOf(txtnip.getText());
        String pai = txtnomedopai.getText();
        String mae = txtnomedamae.getText();
        String bi = txtbi.getText();
        String municipio = txtmunicipio.getText();
        String provincia = txtprovincia.getText();
        String categoria = (String) cbcargo.getSelectedItem();
        String senha = (String) txtsenha.getText();
        String usuario = (String) txtusuario.getText();
        String telefone = txttelefone.getText();

        if (!bi.isEmpty() && !nome.isEmpty() && !pai.isEmpty()
                && !telefone.isEmpty() && !categoria.isEmpty() && !genero.isEmpty()
                && !senha.isEmpty() && !usuario.isEmpty() && !mae.isEmpty() &&
                !provincia.isEmpty() && !municipio.isEmpty()) {
            m.setBi(bi);
            m.setCategoria(categoria);
            m.setGenero(genero);
            m.setMunicipio(municipio);
            m.setNip(nip);
            m.setNome(nome);
            m.setNome_da_mae(mae);
            m.setNome_do_pai(pai);
            m.setProvincia(provincia);
            m.setSenha(senha);
            m.setTelefone(telefone);
            m.setUsuario(usuario);
            if (id == 1) {
                m.setIdpolicia(codigo);
                c.atualizar(m);
            } else {
                c.guardar(m);
            }
        } else {
            m.mensagem("PRENCHA OS ESPAÇOS VAZIOS");
        }
        pesquisar("");
        limpar();
    }

    public void pesquisar(String pesquisar) {
        Cpolicia f = new Cpolicia();
        DefaultTableModel dt = (DefaultTableModel) tbpolicia.getModel();
        Object[] recebe = {"CODIGO", "NOME", "GENERO","NIP","NOME DO PAI","NOME DA MÃE", "Nº DO BI", 
            "MUNICIPIO","PROVINCIA","CATEGORIA","TELEFONE/EMAIL","USUÁRIO", "SENHA"};
        dt.setColumnIdentifiers(recebe);
        dt.setNumRows(0);
        for (Mpolicia m : f.pesquisar(pesquisar)) {
            Object[] dados={m.getIdpolicia(),m.getNome(),m.getGenero(),m.getNip(),m.getNome_do_pai(),m.getNome_da_mae(),
             m.getBi(),m.getMunicipio(),m.getProvincia(),m.getCategoria(),m.getTelefone(),
             m.getUsuario(),m.getSenha()              
            };
            dt.addRow(dados);
        }
    }

    private void limpar() {
        txtbi.setText("");
        txtnip.setText("");
        txtnome.setText("");
        txtsenha.setText("");
        txttelefone.setText("");
        txtnomedopai.setText("");
        txtnomedamae.setText("");
        txtusuario.setText("");
        txtprovincia.setText("");
        txtmunicipio.setText("");
        cbcargo.setSelectedIndex(0);
        cbgenero.setSelectedIndex(0);
    }
}
