/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Cautomobilista;
import Control.Cinfracao;
import Control.Clogin;

/**
 *
 * @author ALFREDO CACONDA
 */
public class princpal extends javax.swing.JFrame {

    /**
     * Creates new form princpal
     */
    public princpal() {
        initComponents();
        Control.Clogin l = new Clogin();//INSTANCIAMOS A CLASSE CONTROL DA LOGIN NO CONSTRUTOR
        lbnome.setText(l.recuprarValor(1));//RECUPERAMOS O VALOR DA LOGIN FUNCIONARIO
        lblqtd_carta.setText(new Cinfracao().qtd_carta()+"");
        lblcaducidade.setText(new Cautomobilista().data_de_caducidade()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configurator1 = new datechooser.autorun.Configurator();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        btnproprietario = new rojeru_san.RSButton();
        btnpolicia = new rojeru_san.RSButton();
        btnpolicia1 = new rojeru_san.RSButton();
        lbMinimizar = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblqtd_carta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFechar1 = new javax.swing.JLabel();
        lblcaducidade = new javax.swing.JLabel();
        btnpolicia2 = new rojeru_san.RSButton();
        principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("UTB");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 30, 290, 50);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 20, 48, 48);

        lbnome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnome.setForeground(new java.awt.Color(255, 255, 255));
        lbnome.setText("jLabel1");
        getContentPane().add(lbnome);
        lbnome.setBounds(30, 80, 240, 22);

        btnproprietario.setBackground(new java.awt.Color(0, 0, 204));
        btnproprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PROPRIETARIO.png"))); // NOI18N
        btnproprietario.setText("AUTOMOBILISTA");
        btnproprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproprietarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnproprietario);
        btnproprietario.setBounds(10, 260, 220, 40);

        btnpolicia.setBackground(new java.awt.Color(0, 0, 204));
        btnpolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/policia.png"))); // NOI18N
        btnpolicia.setText("POLICIA");
        btnpolicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpoliciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnpolicia);
        btnpolicia.setBounds(10, 150, 230, 40);

        btnpolicia1.setBackground(new java.awt.Color(0, 0, 204));
        btnpolicia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/policia.png"))); // NOI18N
        btnpolicia1.setText("AGENTE REGULADOR");
        btnpolicia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpolicia1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnpolicia1);
        btnpolicia1.setBounds(10, 210, 220, 40);

        lbMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Minimizar.png"))); // NOI18N
        lbMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(lbMinimizar);
        lbMinimizar.setBounds(760, 10, 20, 20);

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Fechar.png"))); // NOI18N
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        getContentPane().add(lblFechar);
        lblFechar.setBounds(820, 10, 20, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUANTIDADE DE CARTAS APRIENDIDAS :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 420, 280, 17);

        lblqtd_carta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblqtd_carta.setForeground(new java.awt.Color(255, 255, 255));
        lblqtd_carta.setText("jLabel2");
        getContentPane().add(lblqtd_carta);
        lblqtd_carta.setBounds(780, 420, 60, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUANTIDADE DE CARTAS CADUCADAS :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 390, 280, 17);

        lblFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Fechar.png"))); // NOI18N
        lblFechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechar1MouseClicked(evt);
            }
        });
        getContentPane().add(lblFechar1);
        lblFechar1.setBounds(820, 10, 20, 20);

        lblcaducidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblcaducidade.setForeground(new java.awt.Color(255, 255, 255));
        lblcaducidade.setText("jLabel2");
        getContentPane().add(lblcaducidade);
        lblcaducidade.setBounds(780, 390, 60, 17);

        btnpolicia2.setBackground(new java.awt.Color(0, 0, 204));
        btnpolicia2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_private_48px.png"))); // NOI18N
        btnpolicia2.setText("INFRATORES");
        btnpolicia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpolicia2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnpolicia2);
        btnpolicia2.setBounds(10, 320, 220, 40);

        principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N
        getContentPane().add(principal);
        principal.setBounds(0, 0, 848, 530);

        setSize(new java.awt.Dimension(848, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnproprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproprietarioActionPerformed
        // TODO add your handling code here:
        new automobilista().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnproprietarioActionPerformed

    private void btnpoliciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpoliciaActionPerformed
        // TODO add your handling code here:
        new policia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpoliciaActionPerformed

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lbMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(princpal.ICONIFIED);
    }//GEN-LAST:event_lbMinimizarMouseClicked

    private void btnpolicia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpolicia1ActionPerformed
        // TODO add your handling code here:
        new agente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpolicia1ActionPerformed

    private void lblFechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFechar1MouseClicked

    private void btnpolicia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpolicia2ActionPerformed
        // TODO add your handling code here:
        new infracao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpolicia2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new princpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnpolicia;
    private rojeru_san.RSButton btnpolicia1;
    private rojeru_san.RSButton btnpolicia2;
    private rojeru_san.RSButton btnproprietario;
    private datechooser.autorun.Configurator configurator1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbMinimizar;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFechar1;
    private javax.swing.JLabel lblcaducidade;
    private javax.swing.JLabel lblqtd_carta;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel principal;
    // End of variables declaration//GEN-END:variables
}
